(function(){
  'use strict';
  const D=GameData,C=D.Campaign,G=Progress,S=GameScenes, $=s=>document.querySelector(s), main=$('#main'), modal=$('#modal');
  const STORAGE='pvz-allstars-home-v2';let save,legacySave=null,storageOK=true;
  try{const raw=localStorage.getItem('pvz-allstars-home-v1');if(raw)legacySave=D.validateSave(JSON.parse(raw));}catch{} 
  try{const raw=localStorage.getItem(STORAGE);save=raw?D.validateSave(JSON.parse(raw)):D.defaultSave();}catch{save=D.defaultSave();}
  let view='home',mapPage=0,mapWorld=0,selectedPlant=null,selectedSlot=null,battle=null,preview=null,paused=false,speed=1,rafTime=0,lastHUD=0,bannerTimer=0,toastTimer,awarded=false,returnView='adventure',audio=null,backgroundTime=0;
  const art={},parts={},animations=new PlantAnimation.Library({...PlantAnimationData,...ProjectileAnimationData}),weapons=new WeaponView(animations);
  let actorState=null,actors=new Map(),plantFilter="all",plantSearch="",gardenActors=new Map(),gardenFrame=0;
  for(const p of D.plants){const img=new Image();img.src='assets/'+p.id+'-body.png';art[p.id]=img;}
  for(const key of ['frontyard','egypt','pirate']){const img=new Image();img.src='assets/'+key+'.webp';art[key]=img;}
  for(const name of ['head','body','outerarm_upper','outerarm_lower','outerarm_hand','outerleg_upper','outerleg_lower','outerleg_foot','innerleg_upper','innerleg_lower','innerleg_foot','cone1','bucket1']){const img=new Image();img.src='assets/Zombie_'+name+'.png';parts[name]=img;}
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stars=n=>'★'.repeat(n)+'☆'.repeat(Math.max(0,6-n));
  const unlocked=p=>G.owned(save,p.id);
  const stageOpen=i=>C.stageOpen(save,i);
  function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(save));storageOK=true;}catch{storageOK=false;}updateResources();}
  function updateResources(){$('#coins').textContent=save.coins.toLocaleString();$('#essence').textContent=save.essence.toLocaleString();$('#gems').textContent=save.gems.toLocaleString();$('#tickets').textContent=save.tickets.toLocaleString();$('#plant-count').textContent=D.plants.filter(unlocked).length+' / '+D.plants.length;$('#save-status').textContent=storageOK?'✓ 已自动保存':'本次存档未保存';$('#sound').textContent=save.sound?'♫':'♪';$('#sound').setAttribute('aria-label',save.sound?'关闭音效':'开启音效');}
  function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
  function tone(freq=480,duration=.08,type='sine',volume=.025){if(!save.sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(freq,audio.currentTime);oscillator.frequency.exponentialRampToValueAtTime(Math.max(70,freq*.65),audio.currentTime+duration);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+duration);}catch{}}
  function showModal(html){modal.classList.toggle('wide',html.includes('summon-result')||html.includes('draw-history'));$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
  function closeModal(){modal.close();}
  function switchView(next){
    if(battle&&!battle.finished){toast('先结束当前战斗，再切换模式。');return;}view=next;
    document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===(next==='adventure'?'map':next)));
    selectedPlant=null;selectedSlot=null;battle=null;preview=null;if(next==='map'){const st=C.get(save.selectedStage);mapWorld=st.world;mapPage=Math.floor(st.local/10);}render();
  }
  function render(){updateResources();main.dataset.scene=view;G.daily(save);if(view==='garden'){renderGarden();return;}if(view==='home'){main.innerHTML=S.home(save,legacySave);main.onclick=sceneEvents;return;}if(view==='map'){main.innerHTML=S.map(save,mapWorld,mapPage);main.onclick=sceneEvents;return;}if(view==='summon'){main.innerHTML=S.summon(save);main.onclick=sceneEvents;return;}renderAdventure();}
  function sceneEvents(e){const b=e.target.closest('button');if(!b)return;
    if(b.dataset.go)switchView(b.dataset.go);
    if(b.dataset.chapter!==undefined){const wi=+b.dataset.chapter;if(!C.worldOpen(save,wi)){toast('通关前一个世界的全部关卡后开启。');return;}save.selectedStage=C.next(save,wi);persist();switchView('map');}
    if(b.dataset.mapStage!==undefined){const i=+b.dataset.mapStage;if(!stageOpen(i)){toast('先通关前一关，再向前出发。');return;}save.selectedStage=i;persist();render();}
    if(b.dataset.page!==undefined){mapPage=+b.dataset.page;const w=C.worlds[mapWorld],index=w.start+Math.min(w.count-1,mapPage*10);if(stageOpen(index)){save.selectedStage=index;persist();}render();}
    if(b.dataset.homeAction){const action=b.dataset.homeAction;({login:showLogin,quests:showQuests,stars:showStarRewards,'draw-rules':showDrawRules,legacy:restoreLegacy})[action]?.();}
    if(b.dataset.draw){try{const results=G.draw(save,b.dataset.draw,+b.dataset.count,{free:b.dataset.free==='true'});persist();render();showModal(S.results(results));tone(results.some(r=>r.grade==='SSR')?1000:680,.3,'triangle');}catch(err){toast(err.message);}}
  }
  function showLogin(){G.daily(save);const done=save.daily.claimDay===G.day(),streak=done?save.daily.streak:save.daily.claimDay===G.day(Date.now()-86400000)?save.daily.streak%7+1:1;showModal('<div class="modal-inner"><h2>每日签到</h2><p>连续回来守护草坪，收下七天的礼物。</p><div class="login-grid">'+G.LOGIN.map((r,i)=>'<div class="'+(streak===i+1?'today':'')+'"><b>第 '+(i+1)+' 天</b><span>'+G.rewardText(r)+'</span></div>').join('')+'</div><div class="modal-buttons"><button class="modal-close" data-action="close">返回</button><button class="primary-btn" data-action="claim-login" '+(done?'disabled':'')+'>'+(done?'今天已领取':'领取第 '+streak+' 天奖励')+'</button></div></div>');}
  function showQuests(){G.daily(save);showModal('<div class="modal-inner"><h2>每日任务</h2><p>每天北京时间 00:00 刷新</p><div class="quest-list">'+G.QUESTS.map(q=>'<div><b>'+q.name+' <small>'+Math.min(q.target,save.daily[q.key])+' / '+q.target+'</small></b><p>'+G.rewardText(q.reward)+'</p><button data-quest="'+q.id+'" '+(save.daily[q.key]<q.target||save.daily.claimed.includes(q.id)?'disabled':'')+'>'+(save.daily.claimed.includes(q.id)?'已领取':'领取')+'</button></div>').join('')+'</div><button class="modal-close" data-action="close">返回主页</button></div>');}
  function showStarRewards(){const wi=C.get(save.selectedStage).world;showModal('<div class="modal-inner"><h2>'+C.worlds[wi].name+' · 星星奖励</h2><p>已获得 '+G.worldStars(save,wi)+' / '+C.worlds[wi].count*3+' 颗星星</p><div class="quest-list">'+G.starRewards(wi).map(r=>'<div><b>★ 集齐 '+r.target+' 星</b><p>'+G.rewardText(r.reward)+'</p><button data-star="'+r.target+'" '+(G.worldStars(save,wi)<r.target||save.starClaims.includes(r.key)?'disabled':'')+'>'+(save.starClaims.includes(r.key)?'已领取':'领取')+'</button></div>').join('')+'</div><button class="modal-close" data-action="close">返回游戏</button></div>');}
  function showDrawRules(){showModal('<div class="modal-inner draw-history"><h2>召唤规则与记录</h2><div class="help-copy"><p><b>友情召唤：</b>R 80% / SR 19% / SSR 1%，召唤券每次 1 张；每日 3 次免费，间隔 10 分钟。</p><p><b>钻石召唤：</b>R 60% / SR 32% / SSR 8%，单次 280 钻石，十连 2,520 钻石；每 48 小时免费 1 次。</p><p>钻石召唤连续 29 次未出 SSR，第 30 次必出；出 SSR 后重新计数。免费钻石召唤也计入保底。两种十连均至少有一位 SR 或 SSR。</p><p>同一品质内每种植物概率相等。以上为普通抽取概率，十连保证和保底会提高高品质的实际占比。重复植物转为专属碎片：R 8 / SR 16 / SSR 32 枚。</p><p>专属碎片用于进化；8 枚可以换 4 枚万能碎片。未获得的 R / SR / SSR 植物分别需 40 / 100 / 240 枚万能碎片合成。</p></div><h3>最近 '+save.draws.history.length+' 次</h3><div class="history-list">'+save.draws.history.map(r=>'<div><span class="grade-'+r.grade+'">'+r.grade+'</span><b>'+D.byId[r.id].name+'</b><small>'+ (r.fresh?'新伙伴':'碎片 +'+r.fragments)+(r.pity?' · 保底':'')+'</small></div>').join('')+'</div><button class="primary-btn" data-action="close">知道了</button></div>');}
  function backupCurrent(){try{localStorage.setItem('pvz-allstars-home-v2-backup',JSON.stringify(save));}catch{} }
  function restoreLegacy(){if(!legacySave)return;showModal('<div class="modal-inner"><h2>恢复上一版旅程？</h2><p>保留了 '+legacySave.owned.length+' 位植物、'+Object.keys(legacySave.cleared).length+' 个通关记录。旧版埃及与海盗进度会映射到相应世界。当前新旅程会自动备份。</p><div class="modal-buttons"><button class="modal-close" data-action="close">取消</button><button class="primary-btn" data-action="restore-legacy">恢复旧旅程</button></div></div>');}
  function refreshAfterClaim(reward){persist();render();toast(G.rewardText(reward));}
  function renderAdventure(){
    const isEndless=view==='endless',stage=isEndless?0:save.selectedStage,st=C.get(stage),wi=st.world,w=D.worlds[wi];
    main.innerHTML=`<div class="map-heading"><button class="wood-button" id="back-map">‹ ${isEndless?'返回主页':'返回主线'}</button><div><h1>${isEndless?'无尽挑战':w.name+' · '+st.label}</h1><p>${isEndless?'僵尸逐波变强，每五波出现首领':st.name+' · '+st.lanes.length+' 路 / '+st.waves+' 波 · 建议 Lv.'+st.recommended}</p></div><button class="wood-button" data-go="garden" id="battle-garden">❋ 培养植物</button></div>
    ${isEndless?`<div class="endless-intro"><div><h2>草坪永不落幕</h2><p>击败僵尸获得金币和精华，培养伙伴，再挑战更远。</p></div><img src="assets/repeater-body.png" alt="双发射手"><div class="endless-best"><b>${save.bestEndless}</b>最高守住波数</div></div>`:''}
    <div class="adventure-layout battle-layout"><section><div class="battle-panel"><div class="board-toolbar"><div class="board-title"><i class="status-dot"></i><span id="battle-status">布阵准备</span><small id="formation-count">${save.team.filter(Boolean).length} / 7 株上阵</small></div><div class="tool-group"><button class="subtle-btn" id="recommend">推荐阵容</button><button class="subtle-btn" id="clear-team">清空阵容</button><button class="subtle-btn ${save.auto?'active':''}" id="auto">自动技能 ${save.auto?'开':'关'}</button></div></div>
    <div class="board-wrap"><canvas id="lawn" width="1100" height="600" aria-label="三路草坪战场"></canvas><div class="board-hud"><div class="hud-chip" id="wave-hud"><b>${isEndless?'无尽挑战':st.label}</b>${isEndless?'守住每一波':st.name}</div><div class="hud-chip" id="lives-hud">♥ ♥ ♥ <span>　保护后院</span></div></div><div class="board-overlay" id="slots"></div><div id="board-banner" class="board-banner hidden"><strong></strong><small></small></div></div>
    <div class="battle-controls"><div class="beans"><span class="beans-label">技能能量豆</span><div class="bean attack"><span></span><b id="bean-attack">2</b><small>攻击</small></div><div class="bean heal"><span></span><b id="bean-heal">1</b><small>治疗</small></div><div class="bean defend"><span></span><b id="bean-defend">1</b><small>防御</small></div></div><div class="battle-right"><button class="subtle-btn" id="speed" aria-label="切换战斗速度">1×</button><button class="subtle-btn" id="pause" hidden>暂停</button><button class="primary-btn" id="start">${isEndless?'开始无尽挑战':'开始战斗'}　▷</button><button class="subtle-btn" id="retreat" hidden>撤退</button></div></div></div>
    <div class="hint-bar"><span id="play-hint">${!isEndless&&st.lanes.length<3?'本关只有'+st.lanes.length+'条路线来袭。':'守护三条路线。'}选中植物，再点草坪格子布阵；板车可跨路支援。</span><span><kbd>↑</kbd><kbd>↓</kbd>板车 <kbd>空格</kbd>暂停</span></div></section></div>
    <section class="team-section"><div class="section-label"><h2 id="deck-title">选择你的植物 <small>同一植物只上阵一次</small></h2><p class="bond">❋ 豌豆 + 向日葵：攻击 +15%</p></div><div id="roster-tools" class="plant-tools"></div><div id="deck"></div></section>`;
    preview=new GameCore.Battle(save,stage,isEndless);renderSlots();renderDeck();bindRosterTools();draw();bindAdventure();
    $('#back-map').onclick=()=>switchView(isEndless?'home':'map');$('#battle-garden').onclick=()=>switchView('garden');
  }
  function renderSlots(){const state=battle||preview,F=D.FIELD;let html='';for(let i=0;i<6;i++){const x=i%2===0?F.rearX:F.frontX,y=state.y(Math.floor(i/2))-44,id=save.team[i];html+=`<button class="deploy-slot ${id?'':'empty'} ${selectedSlot===i?'selected':''}" style="left:${x/F.width*100}%;top:${y/F.height*100}%;width:${F.cellWidth/F.width*100}%;height:${F.rowHeight/F.height*100}%" data-slot="${i}" data-label="${id?D.byId[id].name:'点击种植'}" aria-label="${['上','中','下'][Math.floor(i/2)]}路${i%2===0?'后排':'前排'}${id?' '+D.byId[id].name:' 空位'}" ${battle?'hidden':''}></button>`;}const cart=state.units.find(u=>u.slot===6);for(let lane=0;lane<3;lane++){html+=`<button class="cart-lane ${lane===state.cartLane?'active':''}" style="top:${(state.y(lane)-44)/F.height*100}%;height:${F.rowHeight/F.height*100}%" data-lane="${lane}" data-label="${lane===state.cartLane?'板车':'移至此路'}" aria-label="板车移动到${['上','中','下'][lane]}路">${lane===state.cartLane?(cart?'':'＋'):'↕'}</button>`;}if(!battle)html+=`<button class="deploy-slot ${save.team[6]?'':'empty'} ${selectedSlot===6?'selected':''}" style="left:${F.cartX/F.width*100}%;top:${(state.y(save.cartLane)-44)/F.height*100}%;width:7%;height:${F.rowHeight/F.height*100}%" data-slot="6" data-label="板车 · ${save.team[6]?D.byId[save.team[6]].name:'空位'}" aria-label="板车植物${save.team[6]?' '+D.byId[save.team[6]].name:''}"></button>`;$('#slots').innerHTML=html;$('#formation-count').textContent=save.team.filter(Boolean).length+' / 7 株上阵';}
  function renderDeck(){if($('#roster-tools'))$('#roster-tools').hidden=!!battle;if(battle){$('#deck-title').innerHTML='植物必杀技能 <small>点击释放 · 数字键 1–7 · 最多储存 8 颗技能豆</small>';$('#deck').className='skill-deck';$('#deck').innerHTML=save.team.map((id,i)=>id?`<button class="skill-card" data-skill="${i}" aria-label="${i+1} ${D.byId[id].name} ${D.byId[id].skill}"><span class="shortcut">${i+1}</span><img src="assets/${id}-body.png" alt=""><span><b>${D.byId[id].skill}</b><small>${D.byId[id].role==='heal'?'1':'2'} 颗${{attack:'攻击',heal:'治疗',defend:'防御'}[D.byId[id].role]}豆</small></span><span class="cooldown-cover"></span></button>`:'<div></div>').join('');updateHUD();return;}
    $('#deck').className='deck';$('#deck').innerHTML=D.plants.map(p=>`<button class="plant-card ${selectedPlant===p.id?'chosen':''} ${!unlocked(p)?'locked':''}" data-plant="${p.id}" aria-label="选择${p.name}" ${!unlocked(p)?'disabled':''}><span class="level">Lv.${save.levels[p.id]}</span>${save.team.includes(p.id)?'<span class="in-team">✓</span>':''}<img src="assets/${p.id}-body.png" alt="${p.name}"><b>${p.name}</b>${unlocked(p)?`<span class="stars">${'★'.repeat(save.stars[p.id])}</span>`:`<span class="unlock">召唤 / 碎片合成</span>`}</button>`).join('');applyRosterFilter();}
  function bindRosterTools(){
    const tools=$('#roster-tools');if(!tools)return;tools.innerHTML=Object.entries({all:'全部植物',attack:'攻击',heal:'治疗',defend:'防御'}).map(([id,name])=>`<button data-filter="${id}" class="${plantFilter===id?'active':''}" aria-pressed="${plantFilter===id}">${name}</button>`).join('')+'<span class="roster-total"></span>'+`<input type="search" aria-label="搜索植物" placeholder="找一位植物伙伴…" value="${esc(plantSearch)}">`;
    tools.onclick=e=>{const b=e.target.closest('[data-filter]');if(b){plantFilter=b.dataset.filter;applyRosterFilter();}};
    tools.querySelector('input').oninput=e=>{plantSearch=e.target.value.trim();applyRosterFilter();};applyRosterFilter();
  }
  function applyRosterFilter(){
    let shown=0;document.querySelectorAll('.plant-card,.garden-card').forEach(card=>{const p=D.byId[card.dataset.plant||card.dataset.roster];if(!p)return;const match=(plantFilter==='all'||p.role===plantFilter)&&(!plantSearch||p.name.includes(plantSearch));card.hidden=!match;if(match)shown++;});
    document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===plantFilter);b.setAttribute('aria-pressed',String(b.dataset.filter===plantFilter));});
    const total=$('.roster-total');if(total)total.textContent=shown+' / '+D.plants.length+' 种 · '+D.plants.filter(unlocked).length+' 已解锁';
  }
  function bindAdventure(){main.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.world!==undefined||b.dataset.stage!==undefined){if(battle&&!battle.finished)return;battle=null;}if(b.dataset.stage!==undefined){save.selectedStage=+b.dataset.stage;persist();render();}if(b.dataset.plant){selectedPlant=b.dataset.plant;selectedSlot=null;renderSlots();renderDeck();toast('已选择'+D.byId[selectedPlant].name+'，点击草坪格子放置。');}if(b.dataset.slot!==undefined)placePlant(+b.dataset.slot);if(b.dataset.lane!==undefined){const lane=+b.dataset.lane;if(battle){if(battle.moveCart(lane)){renderSlots();tone(300);}}else{save.cartLane=lane;preview=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');persist();renderSlots();}}if(b.dataset.skill!==undefined)useSkill(+b.dataset.skill);};
    $('#recommend').onclick=()=>{if(battle)return;save.team=G.recommend(save);selectedPlant=null;selectedSlot=null;save.cartLane=0;persist();preview=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');renderSlots();renderDeck();toast('已按拥有的植物安排阵容；板车可支援空缺路线。');};
    $('#clear-team').onclick=()=>{if(battle)return;save.team=Array(7).fill(null);selectedPlant=null;persist();preview=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');renderSlots();renderDeck();};
    $('#auto').onclick=()=>{save.auto=!save.auto;if(battle)battle.auto=save.auto;persist();$('#auto').classList.toggle('active',save.auto);$('#auto').textContent='自动技能 '+(save.auto?'开':'关');};
    $('#speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('#speed').textContent=speed+'×';};$('#start').onclick=startBattle;$('#pause').onclick=togglePause;$('#retreat').onclick=()=>{if(battle&&!battle.finished)showModal('<div class="modal-inner"><h2>返回后院？</h2><p>这场战斗尚未结束，撤退不会消耗金币。<br>当前关卡进度会重新开始。</p><div class="modal-buttons"><button class="modal-close" data-action="close">继续战斗</button><button class="primary-btn" data-action="retreat">返回布阵</button></div></div>');};
  }
  function placePlant(slot){if(battle)return;if(selectedPlant){const old=save.team.indexOf(selectedPlant);if(old===slot){selectedPlant=null;selectedSlot=slot;renderDeck();renderSlots();return;}if(old!==-1){const swap=save.team[slot];save.team[old]=swap;}save.team[slot]=selectedPlant;selectedPlant=null;selectedSlot=slot;persist();preview=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');renderSlots();renderDeck();tone(560);$('#play-hint').textContent='已布置。再次点击当前格子可移除植物，或选择另一株来替换。';}else if(selectedSlot===slot){save.team[slot]=null;selectedSlot=null;persist();preview=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');renderSlots();renderDeck();}else{selectedSlot=slot;renderSlots();toast('选中'+(save.team[slot]?D.byId[save.team[slot]].name:'空位')+'，可选植物替换；再点一次移除。');}}
  function startBattle(){if(save.team.filter(Boolean).length<3){toast('至少布置 3 株植物才能出发。');return;}const lanes=view==='endless'?[0,1,2]:C.get(save.selectedStage).lanes;const empty=lanes.filter(l=>!save.team[l*2]&&!save.team[l*2+1]&&!(save.team[6]&&save.cartLane===l));if(empty.length){toast('来袭路线都需要植物守护；点推荐阵容或安排板车支援。');return;}battle=new GameCore.Battle(save,view==='endless'?0:save.selectedStage,view==='endless');paused=false;awarded=false;returnView=view;$('#start').hidden=true;$('#pause').hidden=false;$('#retreat').hidden=false;$('#recommend').disabled=true;$('#clear-team').disabled=true;document.querySelectorAll('[data-world],[data-stage]').forEach(el=>el.disabled=true);$('#battle-status').textContent='战斗进行中';$('#formation-count').textContent='植物会自动攻击';$('#play-hint').textContent='点击下方技能卡释放必杀。移动板车支援薄弱的路，别忘了治疗前排。';renderSlots();renderDeck();showBanner('植物们，出发！','守住 '+battle.lanes.length+' 条路线，保护后院',1.5);tone(720,.25);}
  function togglePause(){if(!battle||battle.finished)return;paused=!paused;$('#pause').textContent=paused?'继续':'暂停';$('#battle-status').textContent=paused?'战斗已暂停':'战斗进行中';if(paused)showBanner('休息一下','点击继续或按空格返回战斗',9999);else hideBanner();}
  function showBanner(title,sub,ttl){const el=$('#board-banner');if(!el)return;el.querySelector('strong').textContent=title;el.querySelector('small').textContent=sub;el.classList.remove('hidden');bannerTimer=ttl;}
  function hideBanner(){$('#board-banner')?.classList.add('hidden');bannerTimer=0;}
  function useSkill(slot){if(!battle||battle.finished||paused)return;const u=battle.units.find(u=>u.slot===slot);if(!u||u.hp<=0){toast('这株植物已经倒下。');return;}const p=D.byId[u.plant];if(u.skillCooldown>0){toast('必杀还在冷却中。');return;}if(battle.beans[p.role]<(p.role==='heal'?1:2)){toast('对应职业的能量豆不足。');return;}battle.skill(slot);updateHUD();}
  function updateHUD(){if(!battle)return;for(const role of ['attack','heal','defend'])$('#bean-'+role).textContent=battle.beans[role];$('#wave-hud').innerHTML=`<b>第 ${battle.wave||1} 波${battle.endless?'':' / '+battle.maxWaves}</b>消灭 ${battle.kills} · ${Math.floor(battle.time)} 秒`;$('#lives-hud').innerHTML='♥ '.repeat(Math.max(0,battle.lives))+'<span>　保护后院</span>';document.querySelectorAll('[data-skill]').forEach(el=>{const u=battle.units.find(u=>u.slot===+el.dataset.skill);if(!u)return;const p=D.byId[u.plant],ready=u.hp>0&&u.skillCooldown===0&&battle.beans[p.role]>=(p.role==='heal'?1:2);el.classList.toggle('ready',ready);el.classList.toggle('down',u.hp<=0);el.querySelector('.cooldown-cover').style.height=(u.skillCooldown/6*100)+'%';el.querySelector('small').textContent=u.hp<=0?'已倒下':u.skillCooldown>0?'冷却 '+Math.ceil(u.skillCooldown)+' 秒':(p.role==='heal'?'1':'2')+' 颗'+{attack:'攻击',heal:'治疗',defend:'防御'}[p.role]+'豆';});}
  function handleEvents(){for(const e of battle.drainEvents()){if(e.unitId){syncActors(battle);actors.get(e.unitId)?.act(e.type==='skill'?'skill':e.type==='plantDown'?'death':e.mode||'attack',e.clip);}if(e.type==='wave')showBanner('第 '+e.wave+' 波来袭',e.wave===battle.maxWaves&&!battle.endless?'最后一波，守住防线！':'植物伙伴准备就绪',1.3);if(e.type==='skill'){toast(e.skill+'！');tone(850,.18,'triangle');}if(e.type==='bean')tone(550,.07);if(e.type==='plantDown')toast(D.byId[e.plant].name+'倒下了，及时支援这条路！');if(e.type==='boss'){showBanner('巨人重击','前排受到冲击，注意治疗！',1.1);tone(100,.25,'sawtooth',.03);}if(e.type==='breach'){toast('一只僵尸突破了防线！');tone(160,.2,'square');}if(e.type==='finish')finishBattle();}}
  function finishBattle(){if(awarded)return;awarded=true;updateHUD();hideBanner();const r=battle.result,{reward,newPlants}=G.finish(save,battle.stage,r,battle.endless);persist();$('#battle-status').textContent=battle.endless?'挑战结束':r.win?'战斗胜利':'防线失守';$('#pause').hidden=true;$('#retreat').hidden=true;tone(r.win?800:240,.35);
    showModal(`<div class="modal-inner"><div class="eyebrow">${battle.endless?'ENDLESS CHALLENGE':r.win?'VICTORY':'TRY AGAIN'}</div><img class="hero-art" src="assets/${r.win?'sunflower':'wallnut'}-body.png" alt=""><h2>${battle.endless?'挑战结算':r.win?'这片草坪，守住了！':'调整阵容，再战一次'}</h2>${!battle.endless?`<div class="modal-stars">${'★'.repeat(r.stars)+'☆'.repeat(3-r.stars)}</div>`:`<p>最高记录：守住 ${save.bestEndless} 波</p>`}<div class="result-stats"><span><b>${r.kills}</b>击败僵尸</span><span><b>${r.time}s</b>战斗时长</span><span><b>${r.alive} / ${battle.units.length}</b>存活伙伴</span></div><div class="result-rewards">${G.rewardText(reward)}</div>${newPlants.length?`<div class="result-new">✦ 新伙伴：${newPlants.map(id=>D.byId[id].name).join('、')}，已自动加入阵容</div>`:''}<div class="modal-buttons"><button class="modal-close" data-action="formation">返回布阵</button><button class="primary-btn" data-action="${r.win&&!battle.endless?'next':'garden'}">${r.win&&!battle.endless?'主线 · 下一站':'培养植物'}</button></div></div>`);
  }
  function renderGarden(){main.onclick=null;main.innerHTML=`<div class="map-heading"><button class="wood-button" id="return-adventure">‹ 返回主页</button><div><h1>植物花园</h1><p>升级、进化，把每一位伙伴培养成全明星</p></div><button class="wood-button" id="garden-summon">★ 召唤伙伴</button></div><div class="unlocked-banner">❋ 已拥有 ${save.owned.length} / 36 位伙伴 <span>最高 Lv.${D.MAX_LEVEL} / 6 星 · 万能碎片 ${save.shards} · 精华 ${save.essence}</span></div><div id="roster-tools" class="plant-tools"></div><div class="garden-grid">${D.plants.map(p=>{const s=D.stats(p.id,save),open=unlocked(p),lv=save.levels[p.id],rank=save.stars[p.id],cost=upgradeCost(p.id),ec=G.evolveCost(save,p.id),craft=D.fragmentCost(p);return `<article data-roster="${p.id}" class="garden-card ${open?'':'locked'}"><div class="plant-art"><img src="assets/${p.id}-body.png" alt="${p.name}"><canvas class="plant-preview" data-preview="${p.id}" width="180" height="150" aria-label="${p.name}待机动画"></canvas><span class="grade-badge grade-${D.grade(p)}">${D.grade(p)}</span></div><h2>${p.name}<small>${open?'Lv.'+lv:'未获得'}</small></h2><span class="role-tag ${p.role}">${D.roleNames[p.role]} · ${p.element}</span><div class="garden-stars">${stars(rank)}</div><div class="stat-row"><span>生命<b>${s.hp}</b></span><span>攻击<b>${s.atk}</b></span></div><p>${p.desc}</p><div class="fragment-row">专属碎片：${save.fragments[p.id]} ${open&&save.fragments[p.id]>=8?`<button data-exchange="${p.id}">8 换 4 万能</button>`:''}</div><div class="garden-actions">${open?`<button data-upgrade="${p.id}" ${lv>=D.MAX_LEVEL||save.coins<cost?'disabled':''}>${lv>=D.MAX_LEVEL?'已满级':'升级 · '+cost+' 金币'}</button><button data-evolve="${p.id}" ${rank>=6||save.essence<ec.essence||save.fragments[p.id]<ec.fragments?'disabled':''}>${rank>=6?'满星伙伴':'进化 · '+ec.essence+' 精华 / '+ec.fragments+' 碎片'}</button>`:`<button data-craft="${p.id}" ${save.shards<craft?'disabled':''}>合成 · ${craft} 万能碎片</button><button data-garden-draw="true">去召唤</button>`}</div></article>`;}).join('')}</div>`;bindRosterTools();$('#return-adventure').onclick=()=>switchView('home');$('#garden-summon').onclick=()=>switchView('summon');main.onclick=e=>{const b=e.target.closest('button');if(!b)return;try{
      if(b.dataset.upgrade){const id=b.dataset.upgrade,cost=upgradeCost(id);if(!G.owned(save,id)||save.coins<cost||save.levels[id]>=D.MAX_LEVEL)return;save.coins-=cost;save.levels[id]++;persist();renderGarden();tone(640,.12);toast(D.byId[id].name+'升级到 Lv.'+save.levels[id]);}
      if(b.dataset.evolve){G.evolve(save,b.dataset.evolve);persist();renderGarden();tone(920,.2);toast('植物进化成功！');}
      if(b.dataset.exchange){G.exchange(save,b.dataset.exchange);persist();renderGarden();toast('已获得 4 枚万能碎片。');}
      if(b.dataset.craft){const p=G.craft(save,b.dataset.craft);persist();renderGarden();toast(p.name+'加入了花园！');}
      if(b.dataset.gardenDraw)switchView('summon');
    }catch(err){toast(err.message);}};
  }
  function upgradeCost(id){return 180+save.levels[id]*70;}
  function help(){showModal('<div class="modal-inner"><h2>全明星，重新集结</h2><div class="help-copy"><p><b>三位伙伴出发：</b>豌豆射手、向日葵、坚果。主线前三个奖励节点会带来卷心菜投手、寒冰射手和菜问；其余植物去召唤或用万能碎片合成。</p><p><b>九个世界：</b>通过每个世界的全部关卡开启下一世界。第一段主线从一条路线逐步增加到三条。</p><p><b>六个固定位置 + 板车：</b>点植物，再点格子。防御站前排，攻击和治疗站后排；板车可以跨路移动。出战只需守住本关标明的来袭路线。</p><p><b>自动攻击 + 职业必杀：</b>攻击和防御技能消耗 2 颗对应豆，治疗消耗 1 颗。豆容量 8。可开启自动技能。</p><p><b>三星条件：</b>全员存活且三颗心完好得 3 星；至少六成伙伴存活、剩余两颗心得 2 星；其余胜利得 1 星。</p><p>1–7 释放技能 · ↑↓ 板车移动 · 空格暂停 · A 自动技能 · S 倍速</p></div><button class="primary-btn" data-action="close">出发！</button></div>');}
  function settings(){showModal('<div class="modal-inner"><h2>存档与安装</h2><p>进度保存在当前浏览器。在线版和离线版可通过 JSON 存档互相转移。</p><div class="setting-buttons"><button data-action="export">↓ 导出存档</button><button data-action="import">↑ 导入存档</button><button data-action="install">▣ 安装到桌面 / 主屏幕</button><button data-action="offline">查看离线准备状态</button>'+(GamePWA.hasUpdate()?'<button data-action="update-app">刷新并更新到新版本</button>':'')+(legacySave?'<button data-action="legacy">恢复上一版旅程</button>':'')+'<button data-action="restore-backup">恢复最近一次自动备份</button><button data-action="new-game">重新开始（先自动备份）</button></div><p>清理浏览器数据或换设备前，请先导出存档。</p><button class="modal-close" data-action="close">返回游戏</button></div>');}
  function exportSave(){const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='全明星归来-存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出。');}
  modal.onclick=async e=>{const b=e.target.closest('button');if(!b)return;
    try{
      if(b.dataset.reveal!==undefined){b.classList.add('revealed');b.setAttribute('aria-label',b.querySelector('.card-front b').textContent);tone(680,.1);return;}
      if(b.dataset.quest){const reward=G.claimQuest(save,b.dataset.quest);refreshAfterClaim(reward);showQuests();return;}
      if(b.dataset.star){const reward=G.claimStars(save,C.get(save.selectedStage).world,+b.dataset.star);refreshAfterClaim(reward);showStarRewards();return;}
      const action=b.dataset.action;if(!action)return;
      if(action==='close')closeModal();
      if(action==='retreat'||action==='formation'){closeModal();battle=null;paused=false;view=returnView;render();}
      if(action==='next'){const current=save.selectedStage;closeModal();battle=null;const next=Math.min(C.total-1,current+1);if(stageOpen(next))save.selectedStage=next;persist();switchView('map');if(current===C.total-1)toast('九大世界全部通关，继续收集星星和植物吧！');}
      if(action==='garden'){closeModal();battle=null;switchView('garden');}
      if(action==='export')exportSave();
      if(action==='import'){if(battle&&!battle.finished){toast('结束战斗后再导入存档。');return;}$('#import-file').click();}
      if(action==='reveal-all')modal.querySelectorAll('[data-reveal]').forEach(c=>c.classList.add('revealed'));
      if(action==='summon-done'){closeModal();render();}
      if(action==='claim-login'){const reward=G.claimLogin(save);refreshAfterClaim(reward);showLogin();}
      if(action==='legacy')restoreLegacy();
      if(action==='restore-legacy'){backupCurrent();save=D.validateSave(legacySave);persist();closeModal();switchView('home');toast('旧旅程已恢复。新旅程保存在自动备份中。');}
      if(action==='restore-backup'){const raw=localStorage.getItem('pvz-allstars-home-v2-backup');if(!raw){toast('还没有自动备份。');return;}const restored=D.validateSave(JSON.parse(raw));showModal('<div class="modal-inner"><h2>恢复自动备份？</h2><p>备份包含 '+restored.owned.length+' 位植物、'+Object.keys(restored.cleared).length+' 个通关记录。当前进度会交换保存到备份中。</p><div class="modal-buttons"><button class="modal-close" data-action="close">取消</button><button class="primary-btn" id="backup-confirm">恢复</button></div></div>');$('#backup-confirm').onclick=()=>{backupCurrent();save=restored;persist();closeModal();switchView('home');};}
      if(action==='new-game'){showModal('<div class="modal-inner"><h2>重新从三位伙伴出发？</h2><p>当前进度会自动备份，可以在存档管理里恢复。</p><div class="modal-buttons"><button class="modal-close" data-action="close">取消</button><button class="primary-btn" data-action="confirm-new">重新开始</button></div></div>');}
      if(action==='confirm-new'){backupCurrent();save=D.defaultSave();persist();closeModal();switchView('home');}
      if(action==='install')await GamePWA.install(toast);
      if(action==='offline')toast(GamePWA.status());
      if(action==='update-app'){if(battle&&!battle.finished){toast('先结束战斗，再更新游戏。');return;}persist();GamePWA.update();}
    }catch(err){toast(err.message);}
  };
  $('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw new Error('存档文件过大');const next=D.validateSave(JSON.parse(await file.text()));showModal('<div class="modal-inner"><h2>替换当前进度？</h2><p>此存档包含 '+Object.keys(next.cleared).length+' 个已通关关卡。<br>请确认已导出需要保留的当前存档。</p><div class="modal-buttons"><button class="modal-close" id="import-cancel">取消</button><button class="primary-btn" id="import-confirm">导入并继续</button></div></div>');$('#import-cancel').onclick=closeModal;$('#import-confirm').onclick=()=>{backupCurrent();save=next;persist();closeModal();switchView('home');toast('存档已恢复，欢迎回来。');};}catch(err){toast('导入失败：'+err.message);}e.target.value='';};
  modal.addEventListener('cancel',()=>{if(battle?.finished){battle=null;paused=false;render();}});
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();switchView('home');};$('#sound').onclick=()=>{save.sound=!save.sound;persist();if(save.sound)tone(550);};$('#help').onclick=help;$('#settings').onclick=settings;
  document.addEventListener('keydown',e=>{if(modal.open||['INPUT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'&&battle){e.preventDefault();togglePause();}if(e.code==='ArrowUp'||e.code==='ArrowDown'){if(battle&&!battle.finished&&!paused){e.preventDefault();battle.moveCart(Math.max(0,Math.min(2,battle.cartLane+(e.code==='ArrowUp'?-1:1))));renderSlots();}}if(/^[1-7]$/.test(e.key))useSkill(+e.key-1);if(e.code==='KeyA')$('#auto')?.click();if(e.code==='KeyS')$('#speed')?.click();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&battle&&!battle.finished&&!paused)togglePause();});

  function roundRect(c,x,y,w,h,r=5){c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
  function image(c,img,x,y,w,h){if(img?.complete&&img.naturalWidth)c.drawImage(img,x,y,w,h);}
  function drawBackground(c,state){LawnView.background(c,state,art,!battle);}
  function syncActors(state){
    if(actorState!==state){for(const a of actors.values())a.dispose();actors.clear();actorState=state;animations.flush();}
    for(const u of state.units)if(!actors.has(u.id)){const a=animations.create(u.plant);if(a)actors.set(u.id,a);}
  }
  function drawPlant(c,u,state){
    const y=state.y(u.lane),dead=u.hp<=0,actor=actors.get(u.id),img=art[u.plant],h=u.plant==='tallnut'?120:110;
    c.save();c.translate(u.x,y);c.fillStyle='#36542738';c.beginPath();c.ellipse(0,2,u.plant==='spike'?47:35,9,0,0,Math.PI*2);c.fill();
    if(u.slot===6){c.fillStyle='#98784d';roundRect(c,-44,-1,88,12,3);c.fillStyle='#5f583e';for(const x of [-31,30]){c.beginPath();c.arc(x,13,9,0,Math.PI*2);c.fill();c.fillStyle='#c4be99';c.beginPath();c.arc(x,13,4,0,Math.PI*2);c.fill();c.fillStyle='#5f583e';}}
    if(dead)c.globalAlpha=.25;else if(u.flash>0)c.filter='brightness(1.5)';
    if(actor)actor.draw(c,0,0,105,h);else if(img?.complete&&img.naturalWidth)c.drawImage(img,-58,-h,116,h);
    c.filter='none';c.globalAlpha=1;
    if(u.shield>0&&!dead){c.strokeStyle='#c2eafa99';c.lineWidth=2.5;c.fillStyle='#c2dfe113';c.beginPath();c.ellipse(0,-h*.46,53,h*.56,0,0,Math.PI*2);c.fill();c.stroke();}
    if(!dead){c.fillStyle='#33492b80';roundRect(c,-29,-h-12,58,5,3);c.fillStyle=u.hp/u.maxHp<.3?'#eaa872':'#dcec94';roundRect(c,-29,-h-12,58*u.hp/u.maxHp,5,3);if(u.shield>0){c.fillStyle='#b2d7e6';roundRect(c,-29,-h-6,Math.min(58,58*u.shield/u.maxHp),3,2);}}
    c.restore();
  }
  function drawZombie(c,e,state,alpha=1){const y=state.y(e.lane),s=e.type==='boss'?1.4:e.type==='runner'?.88:1,t=backgroundTime,walk=Math.sin(t*(e.type==='runner'?9:5)+e.id);c.save();c.translate(e.x,y);c.scale(s,s);c.globalAlpha=alpha;c.fillStyle='#243a293e';c.beginPath();c.ellipse(0,13,29,9,0,0,Math.PI*2);c.fill();if(e.flash>0)c.filter='brightness(2)';if(e.freeze>0)c.filter='sepia(.5) hue-rotate(125deg) saturate(1.8)';
    image(c,parts.innerleg_upper,2,-44,18,30);image(c,parts.innerleg_lower,5+walk*2,-20,15,28);image(c,parts.innerleg_foot,-2+walk*3,3,25,14);image(c,parts.body,-13,-82,38,53);image(c,parts.outerleg_upper,-14,-38,21,26);image(c,parts.outerleg_lower,-13-walk*3,-16,15,24);image(c,parts.outerleg_foot,-25-walk*4,5,29,14);image(c,parts.outerarm_upper,-16,-79,22,28);image(c,parts.outerarm_lower,-35-(e.acted?8:0),-68+walk*2,31,17);image(c,parts.outerarm_hand,-51-(e.acted?8:0),-70+walk*2,25,20);image(c,parts.head,-32,-125+walk,59,53);
    if(e.type==='cone')image(c,parts.cone1,-31,-151+walk,53,62);if(e.type==='bucket')image(c,parts.bucket1,-29,-141+walk,54,48);if(e.type==='runner'){c.fillStyle='#9c413f';roundRect(c,-26,-128,46,9,3);}if(e.type==='thrower'){c.fillStyle='#746342';roundRect(c,-52,-57,26,24,3);c.fillStyle='#c8b18a';roundRect(c,-50,-61,22,6,2);}if(e.type==='boss'){c.save();c.rotate(-.18);c.fillStyle='#65503c';roundRect(c,-50,-108,12,107,4);c.fillStyle='#858071';roundRect(c,-70,-130,49,30,3);c.restore();}if(C.worlds[state.world].id==='egypt'){c.strokeStyle='#e2d0a299';c.lineWidth=4;for(let yy=-76;yy<-30;yy+=9){c.beginPath();c.moveTo(-14,yy);c.lineTo(22,yy);c.stroke();}}if(C.worlds[state.world].id==='pirate'){c.fillStyle='#404344';c.beginPath();c.moveTo(-36,-126);c.lineTo(-4,-156);c.lineTo(33,-122);c.closePath();c.fill();c.fillStyle='#cfb782';c.font='12px serif';c.fillText('×',-4,-130);}
    c.filter='none';c.fillStyle='#263d2966';roundRect(c,-30,-159,60,5,3);c.fillStyle=e.type==='boss'?'#e1a875':'#e0b796';roundRect(c,-30,-159,60*Math.max(0,e.hp/e.maxHp),5,3);if(e.slow>0||e.freeze>0){c.fillStyle='#d3f7ff';c.font='17px serif';c.fillText('❄',-40,-100);}c.restore();}
  function draw(){const canvas=$('#lawn');if(!canvas)return;const c=canvas.getContext('2d'),state=battle||preview;if(!state)return;syncActors(state);canvas.dataset.animations=[...actors.values()].map(a=>a.entry.plant+':'+a.armature.animation.lastAnimationName).join(',');canvas.dataset.animationCount=actors.size;c.clearRect(0,0,1100,600);drawBackground(c,state);const entities=[...state.units.map(u=>({kind:'plant',data:u})),...state.enemies.map(e=>({kind:'zombie',data:e}))].sort((a,b)=>a.data.lane-b.data.lane||a.data.x-b.data.x);for(const entity of entities)if(entity.kind==='plant')drawPlant(c,entity.data,state);else drawZombie(c,entity.data,state);
    if(!battle)for(const lane of state.lanes){const type=C.get(save.selectedStage).boss&&lane===1?'boss':lane===1&&save.selectedStage>0?'cone':save.selectedStage>1&&lane===2?'bucket':'basic';drawZombie(c,{id:50+lane,type,lane,x:925+lane*22,hp:1,maxHp:1,flash:0,slow:0,freeze:0},state,.75);}
    weapons.sync(state,0);canvas.dataset.projectiles=state.shots.filter(s=>s.delay<=0).map(s=>s.butter?"kernel:butter":s.flaming?"fire":s.kind).join(",");for(const shot of state.shots)weapons.drawShot(c,shot);
    for(const f of state.fx){c.save();const ttl=Math.min(1,f.ttl);c.globalAlpha=ttl;c.fillStyle=f.color;c.strokeStyle=f.color;if(f.kind==='number'){c.textAlign='center';c.font='bold 17px Microsoft YaHei';c.lineWidth=3;c.strokeStyle='#33442a66';c.strokeText(f.text,f.x,f.y-(1-ttl)*25);c.fillText(f.text,f.x,f.y-(1-ttl)*25);}if(f.kind==='ring'||f.kind==='burst'||f.kind==='heal'){c.lineWidth=f.kind==='heal'?3:5;c.beginPath();c.arc(f.x,f.y,(1-ttl)*75+10,0,Math.PI*2);c.stroke();if(f.kind==='heal'){c.font='35px serif';c.fillText('+',f.x-10,f.y);}}if(f.kind==='lightning'){c.strokeStyle=f.color;c.lineWidth=3;c.beginPath();c.moveTo(f.x,f.y);for(let i=1;i<=6;i++){c.lineTo(f.x+(f.x2-f.x)*i/6,f.y+(f.y2-f.y)*i/6+(i===6?0:(i%2?12:-12)));}c.stroke();}if(f.kind==='beam'&&!weapons.drawEffect(c,f)){c.globalAlpha=ttl*.65;const g=c.createLinearGradient(f.x,0,Math.min(1080,f.x+(f.length||850)),0);g.addColorStop(0,f.color);g.addColorStop(1,f.color+'00');c.fillStyle=g;c.fillRect(f.x,f.y-8,Math.min(1080-f.x,f.length||850),16);}if(f.kind==='hit'){c.lineWidth=4;for(let i=0;i<4;i++){c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.x+Math.cos(i*1.57)*25,f.y+Math.sin(i*1.57)*25);c.stroke();}}if(f.kind==='explosion'){const radius=(1-ttl)*180+35;const gradient=c.createRadialGradient(f.x,f.y,5,f.x,f.y,radius);gradient.addColorStop(0,'#fff2bc');gradient.addColorStop(.4,f.color);gradient.addColorStop(1,'#ffc56a00');c.fillStyle=gradient;c.beginPath();c.arc(f.x,f.y,radius,0,Math.PI*2);c.fill();}c.restore();}
  }
  function frame(time){const realDt=Math.min(.1,(time-rafTime)/1000||.016);rafTime=time;const running=!battle||(!battle.finished&&!paused&&!modal.open),dt=running?realDt*(battle?speed:1):0;if(running)backgroundTime+=dt;
    const state=battle||preview;if(state&&['adventure','endless'].includes(view))syncActors(state);
    if(battle&&!battle.finished&&!paused&&!modal.open){const steps=Math.ceil(dt/.033);for(let i=0;i<steps;i++){
      for(const u of battle.units){const a=actors.get(u.id);if(a){a.update(dt/steps);u.muzzle=a.point(CombatData[u.plant]?.muzzle,u.x,battle.y(u.lane));if(u.plant==='threepeater'){u.muzzles={};for(const [lane,name] of [[0,'mouthHoleL'],[1,'mouthHoleM'],[2,'mouthHoleR']])u.muzzles[lane]=a.point(name,u.x,battle.y(u.lane));}}}
      battle.update(dt/steps);handleEvents();weapons.sync(battle,dt/steps);if(battle.finished)break;
    }lastHUD+=realDt;if(lastHUD>.15){lastHUD=0;updateHUD();}}
    else if(state&&['adventure','endless'].includes(view)&&!battle)for(const a of actors.values())a.update(dt);
    animations.flush();if(bannerTimer>0&&!paused&&!modal.open){bannerTimer-=realDt;if(bannerTimer<=0)hideBanner();}draw();animateGarden(realDt);requestAnimationFrame(frame);
  }
  function animateGarden(dt){
    if(view!=='garden'){if(gardenActors.size){for(const a of gardenActors.values())a.dispose();gardenActors.clear();animations.flush();}return;}
    gardenFrame+=dt;if(gardenFrame<1/15)return;const elapsed=gardenFrame;gardenFrame=0;
    document.querySelectorAll('[data-preview]').forEach(canvas=>{const rect=canvas.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)return;const id=canvas.dataset.preview;let a=gardenActors.get(id);if(!a){a=animations.create(id);if(a)gardenActors.set(id,a);}if(!a)return;a.update(elapsed);const c=canvas.getContext('2d');c.clearRect(0,0,180,150);a.draw(c,90,146,142,133);canvas.dataset.animation=a.armature.animation.lastAnimationName;canvas.parentElement.classList.add('animated');});
  }
  animations.load().then(()=>{draw();});
  window.addEventListener('game-update-ready',()=>toast('新版本已就绪，可在存档与安装中刷新更新。'));
  render();persist();requestAnimationFrame(frame);
})();
