'use strict';
const assert=require('node:assert/strict'),D=require('./data.js'),C=D.Campaign,G=require('./progress.js'),M=require('./combat-data.js'),{Battle}=require('./engine.js');
function run(b){for(let i=0;i<18000&&!b.finished;i++)b.update(1/30);return b.result;}
assert.deepEqual(C.worlds.map(w=>w.count),[15,20,25,30,30,30,30,30,30]);assert.equal(C.total,240);
let s=D.defaultSave();assert.deepEqual(s.owned,['pea','sunflower','wallnut']);assert(!C.stageOpen(s,1));assert(!C.worldOpen(s,1));
for(let stage=0;stage<6;stage++){const b=new Battle(s,stage),r=run(b);assert(r?.win,'新手无法推进 '+stage);const reward=G.finish(s,stage,r);assert(reward.first);const gems=s.gems;G.finish(s,stage,r);assert.equal(s.gems,gems);if(stage>=3)for(const id of s.owned)s.levels[id]=1+stage;}
assert.equal(s.owned.length,6);assert(G.recommend(s).every(id=>!id||s.owned.includes(id)));console.log('PASS 三株开局、主线前六关、赠卡与首通奖励去重');
const now=Date.UTC(2026,9,7,5);s=D.defaultSave();G.draw(s,'normal',1,{free:true,now,random:()=>.99});assert.equal(s.tickets,3);assert.throws(()=>G.draw(s,'normal',1,{free:true,now:now+1000}));assert(G.availability(s,'normal',now+600000).free);
s.gems=6000;s.draws.pity=29;let results=G.draw(s,'premium',1,{now,random:()=>.99});assert.equal(results[0].grade,'SSR');assert(results[0].pity);assert.equal(s.draws.pity,0);const gems=s.gems;results=G.draw(s,'premium',10,{now,random:()=>.99});assert(results.some(r=>r.grade!=='R'));assert.equal(s.gems,gems-2520);
G.draw(s,'premium',1,{free:true,now,random:()=>.99});assert.throws(()=>G.draw(s,'premium',1,{free:true,now:now+1000}));const reload=D.validateSave(s);assert.deepEqual(reload.draws,s.draws);assert.deepEqual(reload.owned,s.owned);assert.deepEqual(reload.fragments,s.fragments);
const poor=D.defaultSave();assert.throws(()=>G.draw(poor,'normal',10,{now}));assert.equal(poor.tickets,3);poor.fragments.pea=16;G.exchange(poor,'pea');assert.equal(poor.shards,4);G.evolve(poor,'pea');assert.equal(poor.stars.pea,3);poor.shards=40;G.craft(poor,'kernel');assert(poor.owned.includes('kernel'));assert.equal(poor.shards,0);assert.throws(()=>G.craft(poor,'kernel'));
G.claimLogin(poor,now);assert.throws(()=>G.claimLogin(poor,now));G.daily(poor,now+86400000);assert.equal(poor.daily.draws,0);console.log('PASS 免费召唤间隔、30 抽保底、十连保证、货币扣除、碎片与存档保留');
const legacy=D.validateSave({version:1,coins:2356,team:['pea','wallnut','snow'],levels:{pea:7},cleared:{0:3,1:3,2:3,3:3,4:3,5:1},selectedStage:6});assert.equal(legacy.coins,2356);assert.equal(legacy.cleared[60],1);assert.equal(legacy.selectedStage,61);assert(C.worldOpen(legacy,3));assert.throws(()=>D.validateSave({version:99}));console.log('PASS 旧存档迁移与九世界进度映射');
s=D.defaultSave();const b=new Battle(s,0);b.auto=false;b.waveWait=999;b.units.forEach(u=>u.cooldown=999);b.spawn({type:'basic',lane:0});const u=b.units[0],e=b.enemies[0];u.muzzle={x:277,y:141};e.x=700;e.speed=0;e.hp=99999;b.attack(u,D.byId.pea,e);assert.equal(b.shots.length,0);for(let i=0;i<14;i++)b.update(1/30);assert.equal(b.shots.length,0);b.update(1/30);b.update(1/30);assert.equal(b.shots[0].startX,277);assert.equal(M.pea.release,.5);assert.equal(M.melon.release,20/30);console.log('PASS 原生动作发射时机与口部位置');
require('./animation-tests.cjs');
const fs=require('node:fs'),vm=require('node:vm');let context={self:{}};vm.runInNewContext(fs.readFileSync('precache-manifest.js','utf8'),context);const cache=context.self.ALLSTARS_PRECACHE;assert(cache.files.length>100);for(const f of cache.files){assert(fs.existsSync(f),'离线文件缺失 '+f);assert(!f.startsWith('/'),'GitHub 子目录路径错误 '+f);assert(!f.startsWith('research/'));}for(const match of fs.readFileSync('index.html','utf8').matchAll(/(?:src|href)="([^"#]+)"/g))assert(cache.files.includes(match[1]),'页面引用未加入离线清单 '+match[1]);const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');for(const icon of manifest.icons)assert(fs.existsSync(icon.src));console.log('PASS PWA 离线清单、安装图标及 GitHub Pages 相对路径');
